version: '3.8'

services:
  app:
    build: .
    container_name: laravel_app
    volumes:
      - /c/wamp64/www/my-app:/var/www/html
      - ./docker/odbc/odbc.ini:/etc/odbc.ini
      - ./docker/odbc/odbcinst.ini:/etc/odbcinst.ini
    ports:
      - "8080:80"
    environment:
      - DB_CONNECTION=informix
      - DB_HOST=10.129.1.106
      - DB_PORT=9088
      - DB_DATABASE=tbsai
      - DB_USERNAME=informix
      - DB_PASSWORD=651419abc
