export const permissionGroups = {
    "Personal Interno": [
        "personal_interno.ver",
        "personal_interno.crear",
        "personal_interno.editar",
        "personal_interno.eliminar",
        "personal_interno.eliminados",
        "personal_interno.restaurar",
    ],
    Lecturadores: [
        "lecturadores.ver",
        "lecturadores.crear",
        "lecturadores.editar",
        "lecturadores.eliminar",
        "lecturadores.eliminados",
        "lecturadores.restaurar",
    ],
    Zona: [
        "zona.ver",
        "zona.crear",
        "zona.editar",
        "zona.eliminar",
        "zona.eliminados",
        "zona.restaurar",
    ],
    Predios: [
        "predios.ver",
        "predios.crear",
        "predios.editar",
        "predios.eliminar",
        "predios.eliminados",
        "predios.restaurar",
    ],
    Instalaciones: [
        "instalaciones.ver",
        "instalaciones.crear",
        "instalaciones.editar",
        "instalaciones.eliminar",
        "instalaciones.eliminados",
        "instalaciones.restaurar",
    ],
    Asignaciones: [
        "asignaciones.ver",
        "asignaciones.crear",
        "asignaciones.editar",
        "asignaciones.eliminar",
        "asignaciones.eliminados",
        "asignaciones.restaurar",
    ],
    Usuarios: [
        "usuarios.ver",
        "usuarios.crear",
        "usuarios.editar",
        "usuarios.eliminar",
        "usuarios.eliminados",
        "usuarios.restaurar",
    ],
    Productos: [
        "productos.ver",
        "productos.crear",
        "productos.editar",
        "productos.eliminar",
        "productos.eliminados",
        "productos.restaurar",
    ],
};
