export const permissionLabels = {
    "personal_interno.view": "Ver listado de personal",
    "personal_interno.show": "Ver detalle de personal",
    "personal_interno.create": "Crear nuevo personal",
    "personal_interno.edit": "Editar personal",
    "personal_interno.delete": "Eliminar personal",
    "personal_interno.view_deleted": "Ver personal eliminado",
    "personal_interno.restore": "Restaurar personal eliminado",
    // Nuevos permisos para lecturadores
    "lecturadores.view": "Ver listado de lecturadores",
    "lecturadores.show": "Ver detalle de lecturador",
    "lecturadores.create": "Crear nuevo lecturador",
    "lecturadores.edit": "Editar lecturador",
    "lecturadores.delete": "Eliminar lecturador",
    "lecturadores.view_deleted": "Ver lecturadores eliminados",
    "lecturadores.restore": "Restaurar lecturador eliminado",
    "zona.index": "Ver lista de zonas",
    "zona.ver": "Ver zona",
    "zona.crear": "Crear zona",
    "zona.editar": "Editar zona",
    "zona.eliminar": "Eliminar zona",
    "zona.restaurar": "Restaurar zona",
    "predios.index": "Ver lista de predios",
    "predios.ver": "Ver detalle de predio",
    "predios.crear": "Crear predio",
    "predios.editar": "Editar predio",
    "predios.eliminar": "Eliminar predio",
    "predios.restaurar": "Restaurar predio",
    // Permisos para instalaciones
    "instalaciones.index": "Ver lista de instalaciones",
    "instalaciones.ver": "Ver detalle de instalación",
    "instalaciones.crear": "Crear instalación",
    "instalaciones.editar": "Editar instalación",
    "instalaciones.eliminar": "Eliminar instalación",
    "instalaciones.restaurar": "Restaurar instalación",
    "asignaciones.view": "Ver listado de asignaciones",
    "asignaciones.show": "Ver detalle de asignación",
    "asignaciones.create": "Crear nueva asignación",
    "asignaciones.edit": "Editar asignación",
    "asignaciones.delete": "Eliminar asignación",
    "asignaciones.view_deleted": "Ver asignaciones eliminadas",
    "asignaciones.restore": "Restaurar asignación eliminada",

    "usuarios.view": "Ver lista de usuarios",
    "usuarios.show": "Ver detalle de usuario",
    "usuarios.create": "Crear nuevo usuario",
    "usuarios.edit": "Editar usuario",
    "usuarios.delete": "Eliminar usuario",
    "usuarios.view_deleted": "Ver usuarios eliminados",
    "usuarios.restore": "Restaurar usuario eliminado",
};
