<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Aviso extends Model
{
    use HasFactory;

    protected $table = 'aviso';
    protected $primaryKey = 'id_aviso';
    public $incrementing = true;
    protected $keyType = 'int';
    public $timestamps = false;

    // Campos asignables masivos
    protected $fillable = [
        'anio',
        'mes_factura',
        'fecha_genera',
        'fecha_entrega',
        'fecha_vence',
        'fecha_corte',
        'fecha_lect_antes',
        'fecha_lect_actual',
        'importe_mora',
        'num_factu_moras',
        'cmor',
        'ncnt',
        'cod_servicio',
        'ciudad',
        'unid_vecinal',
        'manzana',
        'lote',
        'barrio',
        'dir_socio',
        'nombre_zona',
        'nombre_ruta',
        'zona',
        'ruta',
        'nro_casa',
        'nro_instalacion',
        'cobranza',
        'cod_fijo',
        'clase',
        'importe_vejez',
        'cod_per',
        'cod_socio',
        'nro_predio',
        'nro_instala_predio',
        'nomb_socio',
        'nro_medidor',
        'lect_max',
        'kvat',
        'lect_anterior',
        'lect_actual',
        'consumo',
        'importe_total',
        'imp_credfiscal',
        'cod_observa',
        'estado',
        'nro_factura',
        'latitud',
        'longitud',
        'nro_categoria',
        'nomb_categoria',
        'nro_paginacion',
        'distritos',
        'envio_facturas',
        'usuario',
        'dimension_medidor',
        'estado_agua',
        'estado_alcanta',
        'consumo_promedio',
        'nro_identifica',
        'hora',
        
    ];
     protected $hidden = [
        'bshpxnhpf',
        'bshpxanio',
        'bshpxmesf',
        'bshpxfgen',
        'bshpxfent',
        'bshpxfvto',
        'bshpxfcor',
        'bshpxfini',
        'bshpxffin',
        'bshpximor',
        'bshpxnmor',
        'bshpxcmor',
        'bshpxncnt',
        'bshpxnser',
        'bshpxnciu',
        'bshpxnuve',
        'bshpxnmza',
        'bshpxnlot',
        'bshpxnbar',
        'bshpxnimb',
        'bshpxnzon',
        'bshpxnrut',
        'bshpxzona',
        'bshpxruta',
        'bshpxnroc',
        'bshpxnroi',
        'bshpxcbza',
        'bshpxcodf',
        'bshpxclas',
        'bshpxivej',
        'bshpxcper',
        'bshpxcsoc',
        'bshpxnpre',
        'bshpxnins',
        'bshpxnomb',
        'bshpxnmed',
        'bshpxlmax',
        'bshpxkvat',
        'bshpxlant',
        'bshpxlact',
        'bshpxcons',
        'bshpxconp',
        'bshpxicrf',
        'bshpxcobs',
        'bshpxstat',
        'bshpxnfac',
        'bshpxlati',
        'bshpxlong',
        'bshpxncat',
        'bshpxnoca',
        'bshpxnpag',
        'bshpxdist',
        'bshpxcenv',
        'bshpxuser',
        'bshpxdime',
        'bshpxsagu',
        'bshpxsalc',
        'bshpxcpro',
        'bshpxndid',
        'bshpxhora',
    ];
}
